# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\"e\n\nInitParams\x12\x0f\n\x07n_nodes\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x11\n\tnode_time\x18\x03 \x01(\t\x12\x10\n\x08isLeader\x18\x04 \x01(\x08\x12\x10\n\x08list_ids\x18\x05 \x03(\x05\"N\n\x10\x45lectionResponse\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x12\n\nisComplete\x18\x02 \x01(\x08\x12\x13\n\x0bleader_time\x18\x03 \x01(\t\"G\n\x06Symbol\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07node_id\x18\x03 \x01(\x05\x12\x11\n\tnode_time\x18\x04 \x01(\t\"$\n\x0eSymbolResponse\x12\x12\n\nisComplete\x18\x01 \x01(\x08\"+\n\x05\x42oard\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\tnode_time\x18\x02 \x01(\t\"2\n\rBoardResponse\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\x12\x12\n\nisComplete\x18\x02 \x01(\x08\".\n\x08NodeTime\x12\x11\n\tnode_time\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\";\n\x10NodeTimeResponse\x12\x13\n\x0bmaster_time\x18\x01 \x01(\t\x12\x12\n\nisComplete\x18\x02 \x01(\x08\x32\xb1\x01\n\tTicTacToe\x12+\n\tStartGame\x12\x0b.InitParams\x1a\x11.ElectionResponse\x12%\n\tSetSymbol\x12\x07.Symbol\x1a\x0f.SymbolResponse\x12#\n\tListBoard\x12\x06.Board\x1a\x0e.BoardResponse\x12+\n\x0bSetNodeTime\x12\t.NodeTime\x1a\x11.NodeTimeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITPARAMS._serialized_start=14
  _INITPARAMS._serialized_end=115
  _ELECTIONRESPONSE._serialized_start=117
  _ELECTIONRESPONSE._serialized_end=195
  _SYMBOL._serialized_start=197
  _SYMBOL._serialized_end=268
  _SYMBOLRESPONSE._serialized_start=270
  _SYMBOLRESPONSE._serialized_end=306
  _BOARD._serialized_start=308
  _BOARD._serialized_end=351
  _BOARDRESPONSE._serialized_start=353
  _BOARDRESPONSE._serialized_end=403
  _NODETIME._serialized_start=405
  _NODETIME._serialized_end=451
  _NODETIMERESPONSE._serialized_start=453
  _NODETIMERESPONSE._serialized_end=512
  _TICTACTOE._serialized_start=515
  _TICTACTOE._serialized_end=692
# @@protoc_insertion_point(module_scope)
