# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\x12\x0btic_tac_toe\"\x12\n\x10StartGameRequest\"\x13\n\x11StartGameResponse2`\n\x10TicTacToeService\x12L\n\tStartGame\x12\x1d.tic_tac_toe.StartGameRequest\x1a\x1e.tic_tac_toe.StartGameResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTGAMEREQUEST._serialized_start=32
  _STARTGAMEREQUEST._serialized_end=50
  _STARTGAMERESPONSE._serialized_start=52
  _STARTGAMERESPONSE._serialized_end=71
  _TICTACTOESERVICE._serialized_start=73
  _TICTACTOESERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)
